version: '3'
services:
  mongodb:
    image: mongo:4.1
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

  my-app:
    image: naramelo/exammongo:v1.6
    container_name: my-app
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ports:
      - "8081:8081"

networks:
  default:
    driver: bridge


